version: '3.2'
services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - .:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8011:80
    networks:
      default:
        aliases:
          - exprating.lo

  php:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/php-fpm:5.6.40-ol-7-r223-prod'
    ports:
      - 9000:9000
    volumes:
      - .:/app
    tmpfs:
      - /app/var/

  mariadb:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=exprating
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret
    tmpfs:
      - /var/lib/mysql
  mariadb_test:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=exprating_test
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret
    tmpfs:
      - /var/lib/mysql

networks:
  default:
    external:
      name: exprating
