services:
    characteristic.twig_extension:
        class: Exprating\CharacteristicBundle\Twig\CharacteristicExtension
        arguments: ['@twig']
        public: false
        tags:
            - { name: twig.extension }

    characteristic.form.characteristic_search_parameter:
        class: Exprating\CharacteristicBundle\Form\CharacteristicSearchParameterType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
