services:
    search_bundle.sphinx:
        class: Exprating\SearchBundle\Engine\SphinxEngine
        arguments: ['@iakumai.sphinxsearch.search']

    search_bundle.sql:
        class: Exprating\SearchBundle\Engine\SqlEngine
        arguments: ["@doctrine.orm.entity_manager"]

    search_bundle.product_searcher:
        class: Exprating\SearchBundle\ProductSearch\ProductSearch
        arguments: ["@search_engine"]
