<?php

namespace Exprating\CharacteristicBundle\Repository;

/**
 * CategoryCharacteristicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryCharacteristicRepository extends \Doctrine\ORM\EntityRepository
{
}
