<?php

namespace Exprating\CharacteristicBundle\Repository;

/**
 * ProductCharacteristicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCharacteristicRepository extends \Doctrine\ORM\EntityRepository
{
}
