<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDisabledQuery()
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.isPublished = :isPublished')
            ->orderBy('a.createdAt', 'DESC')
            ->setParameter('isPublished', false);
        return $qb->getQuery();
    }
}
