<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Comment;
use AppBundle\Entity\Product;

/**
 * CommentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDisabledQuery()
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.isPublished = :isPublished')
            ->orderBy('a.createdAt', 'DESC')
            ->setParameter('isPublished', false);

        return $qb->getQuery();
    }

    /**
     * @param Product $product
     *
     * @return array|Comment[]
     */
    public function findByProductEnabled(Product $product)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.isPublished = :isPublished')
            ->setParameter('isPublished', true)
            ->andWhere('a.product = :product')
            ->setParameter('product', $product)
            ->orderBy('a.createdAt', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
