<?php

namespace AppBundle\Repository;

/**
 * CreateExpertRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreateExpertRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
