<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * CreateExpertRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreateExpertRequestRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $categoryAdmin
     *
     * @return \Doctrine\ORM\Query
     */
    public function queryByCurator(User $categoryAdmin)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.curator = :user')
            ->andWhere('a.isApproved = :false')
            ->setParameter('user', $categoryAdmin)
            ->setParameter('false', false);

        return $qb->getQuery();
    }
}
