<?php

namespace AppBundle\Repository;

/**
 * PeopleGroupRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeopleGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
