<?php

namespace AppBundle\Repository;

/**
 * ProductEditHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductEditHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
