<?php

namespace AppBundle\Repository;

/**
 * ProductShopPriceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductShopPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
