<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;

/**
 * ProductEditHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductEditHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Product $product
     *
     * @return \Doctrine\ORM\Query
     */
    public function getQueryByProduct(Product $product)
    {
        $query = $this->createQueryBuilder('a')
            ->where('a.product = :product')
            ->setParameter('product', $product)
            ->orderBy('a.createdAt',  'DESC')
            ->getQuery();
        return $query;
    }
}
