<?php

namespace AppBundle\Repository;

/**
 * RatingSettingsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
