<?php

namespace AppBundle\Repository;

/**
 * ratingSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ratingSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
