<?php

namespace AppBundle\Repository;

/**
 * RatingLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
