imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@CharacteristicBundle/Resources/config/services.yml" }
    - { resource: "@ExpratingImportBundle/Resources/config/services.yml" }
    - { resource: "@ExpratingStatisticBundle/Resources/config/services.yml" }
    - { resource: "@ExpratingImportXmlBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enabled: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets:
        version: '%asset_version%'
        base_path: '%asset_base_url%'


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
        - 'Form/fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            import:
                driver: pdo_sqlite
                path: %kernel.root_dir%/data/import_data.db3
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                connection: default
                query_cache_driver:
                    type:                 apc # Required
                    host:                 ~
                    port:                 ~
                    instance_class:       ~
                    class:                ~
                metadata_cache_driver:
                    type:                 apc # Required
                    host:                 ~
                    port:                 ~
                    instance_class:       ~
                    class:                ~
                result_cache_driver:
                    type:                 apc # Required
                    host:                 ~
                    port:                 ~
                    instance_class:       ~
                    class:                ~
            import:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: import
                query_cache_driver:
                    type:                 apc # Required
                    host:                 ~
                    port:                 ~
                    instance_class:       ~
                    class:                ~
                metadata_cache_driver:
                    type:                 apc # Required
                    host:                 ~
                    port:                 ~
                    instance_class:       ~
                    class:                ~
                result_cache_driver:
                    type:                 apc # Required
                    host:                 ~
                    port:                 ~
                    instance_class:       ~
                    class:                ~
                mappings:
                    ExpratingImportBundle: ~

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User

easy_admin:
    entities:
        - AppBundle\Entity\User
        - AppBundle\Entity\Product
        - AppBundle\Entity\Image
        - AppBundle\Entity\Comment
        - AppBundle\Entity\Category
        - AppBundle\Entity\Feedback
        - AppBundle\Entity\Shop
        - AppBundle\Entity\ProductShopPrice
        - AppBundle\Entity\Manufacturer
        - Exprating\CharacteristicBundle\Entity\ProductCharacteristic
        - Exprating\CharacteristicBundle\Entity\Characteristic


knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: :Pagination:twitter_bootstrap_v3_pagination_custom.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            sluggable: true

assetic:
    debug:          '%asset_debug%'
    use_controller: false
    bundles: ['AppBundle']
    filters:
        cssrewrite: ~
    assets:
        common_js:
            inputs:
                - 'js/external/jquery.min.js'
                - 'js/external/jquery.cookie.js'
                - 'js/external/superfish.js'
                - 'js/external/jquery.mmenu.min.all.js'
                - 'js/external/bootstrap332.min.js'
                - 'js/external/jquery.history.js'
                - 'js/common.js'
                - 'js/include/social_wrapper.js'
        product_list_js:
            inputs:
                - 'js/Exp/exp_hide_menu_on_click.js'
                - 'js/Exp/exp_historical.js'
                - 'js/product_list.init.js'
        product_detail_js:
            inputs:
                - 'js/external/jquery.form.min.js'
                - 'js/external/showdown.min.js'
                - 'js/Exp/exp_form_ajax.js'
                - 'js/Exp/exp_ajax_load.js'
                - 'js/product_detail.init.js'
                - 'js/plugins/log_visit.js'
        product_edit_js:
            inputs:
                - 'js/external/jquery-ui.min.js'
                - 'js/external/jquery.ui.widget.js'
                - 'js/external/jquery.iframe-transport.js'
                - 'js/external/jquery.fileupload.js'
                - 'js/external/jquery.colorbox-min.js'
                - 'js/Exp/exp_historical.js'
                - 'js/Exp/exp_form_ajax.js'
                - 'js/Exp/exp_post_ajax.js'
                - 'js/Exp/exp_colorbox.js'
                - 'js/plugins/outer_html.plugin.js'
                - 'js/plugins/update_position.js'
                - 'js/product_edit.init.js'
                - 'js/product_image_import.js'
        product_choose_category_js:
            inputs:
                - 'js/external/jstree.min.js'
                - 'js/Exp/exp_jstree.js'
                - 'js/product_choose_category.init.js'
        want_to_become_expert_request_js:
            inputs:
                - 'js/external/jstree.min.js'
                - 'js/Exp/exp_jstree.js'
                - 'js/want_to_become_expert_request.init.js'
        experts_detail_edit_js:
            inputs:
                 - 'js/external/jquery.ui.widget.js'
                 - 'js/external/jquery.iframe-transport.js'
                 - 'js/external/jquery.fileupload.js'
                 - 'js/experts_detail_edit.init.js'
        curator_wait_list_js:
            inputs:
                - 'js/Exp/exp_historical.js'
                - 'js/curator_wait_list.init.js'
        curator_my_experts_js:
            inputs:
                - 'js/external/jquery.treegrid.min.js'
                - 'js/curator_my_experts.js'
        layout_expert_items_js:
            inputs:
                - 'js/Exp/exp_historical.js'
                - 'js/external/jstree.min.js'
                - 'js/Exp/exp_jstree.js'
                - 'js/layout_expert_items.init.js'
        category_admin_create_js:
            inputs:
                - 'js/external/jstree.min.js'
                - 'js/category_admin_create.init.js'
        category_admin_categories_js:
            inputs:
                - 'js/external/jquery-ui.min.js'
                - 'js/external/select2.full.min.js'
                - 'js/plugins/select2entity.js'
                - 'js/plugins/update_position.js'
                - 'js/Exp/exp_historical.js'
                - 'js/Exp/exp_colorbox.js'
                - 'js/external/jstree.min.js'
                - 'js/external/jquery.form.min.js'
                - 'js/external/jquery.colorbox-min.js'
                - 'js/Exp/exp_form_ajax.js'
                - 'js/Exp/exp_jstree.js'
                - 'js/category_admin_categories.init.js'
        admin_experts_js:
            inputs:
                - 'js/external/select2.full.min.js'
                - 'js/plugins/select2entity.js'
        category_admin_requests_js:
            inputs:
                - 'js/Exp/exp_historical.js'
                - 'js/category_admin_requests.init.js'
        common_css:
            inputs:
                - 'css/external/bootstrap332.min.css'
                - 'css/external/font-awesome.min.css'
                - 'css/external/superfish.css'
                - 'css/external/select2.min.css'
                - 'css/external/colorbox.css'
                - 'css/style.css'
                - 'css/additional_style.css'
                - 'css/external/jquery.mmenu.all.css'
                - 'css/external/jquery-ui.min.css'
                - 'css/external/jquery.treegrid.css'

exprating_search:
    engine: '%search_engine%'

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        original_filter:
            quality: 90
            filters:
                strip: ~

        tree_icon_filter:
            quality: 100
            filters:
                downscale: { max: [24, 24]}
                thumbnail: { size: [24, 24], mode: inset }
                background: { size: [24, 24] color: '#fff' }

        product_list_filter:
            quality: 90
            filters:
                downscale: { max: [280, 250]}
                thumbnail: { size: [280, 250], mode: inset }
                background: { size: [280, 250] color: '#fff' }

        user_list_filter:
            quality: 90
            filters:
                downscale: { max: [90, 90]}
                thumbnail: { size: [90, 90], mode: inset }
                background: { size: [90, 90] color: '#fff' }

        user_list_curator_filter:
            quality: 100
            filters:
                downscale: { max: [45, 45]}
                thumbnail: { size: [45, 45], mode: inset }
                background: { size: [45, 45] color: '#fff' }

        product_filter:
            quality: 90
            filters:
                downscale: { max: [270, 270]}
                thumbnail: { size: [270, 270], mode: inset }
                background: { size: [270, 270] color: '#fff' }

        product_same_filter:
            quality: 100
            filters:
                downscale: { max: [20, 20]}
                thumbnail: { size: [20, 20], mode: inset }
                background: { size: [20, 20] color: '#fff' }

        product_edit_filter:
            quality: 90
            filters:
                downscale: { max: [80, 80]}
                thumbnail: { size: [80, 80], mode: inset }
                background: { size: [80, 80] color: '#fff' }

oneup_uploader:
    mappings:
        gallery:
            frontend: blueimp

sphinxsearch:
    searchd:
        # Host name for your Sphinx daemon
        host: localhost
        # Port number for your Sphinx daemon
        port: 9312
    indexes:
        # List of sphinx index names (key) and entity names (value)
        # to use it in searchEx() method
        expProductIdx: "AppBundle:Product"
        expPartnerProductIdx: "ExpratingImportXmlBundle:PartnerProduct"

twig_cache:
    service: file_system_cache
    strategy: twig_cache.strategy