exprating_staticstic:
    resource: "@ExpratingStatisticBundle/Controller/"
    type:     annotation
    prefix:   /

exprating_import_xml:
    resource: "@ExpratingImportXmlBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /_admin

oneup_uploader:
    resource: .
    type: uploader