exprating_expert:
    resource: "@ExpratingExpertBundle/Controller/"
    type:     annotation
    prefix:   /expert

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /_admin