# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine

    app.product_voter:
        class: AppBundle\Security\ProductVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }