# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine
    assetic.filter.cdnfilter:
        class: AppBundle\Assetic\Filter\AsseticCdnFilter
        arguments: ['%asset_version%', '%commonhost%', '%cdnlayouthost%', '@filesystem', '%kernel.root_dir%/../web']
        tags:
            - { name: assetic.filter, alias: cdnfilter }

