services:
#    exprating_import_xml.example:
#        class: Exprating\ImportXmlBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    exprating_import.xml.xml_reader:
        class: Exprating\ImportXmlBundle\Xml\XmlReader
        arguments: [ '@serializer.encoder.xml' ]
        
    import.command.xml_reader_command:
        class: Exprating\ImportXmlBundle\Command\XmlReaderCommand
        calls:
            - [setEm, ['@doctrine.orm.entity_manager']]
            - [setXmlReader, ['@exprating_import.xml.xml_reader']]
            - [setSlugify, ['@appbundle.slugify']]
        tags:
            -  { name: console.command }

    import.command.xml_reader_actionpay_command:
        class: Exprating\ImportXmlBundle\Command\XmlReaderActionpayCommand
        calls:
            - [setEm, ['@doctrine.orm.entity_manager']]
            - [setXmlReader, ['@exprating_import.xml.xml_reader']]
            - [setSlugify, ['@appbundle.slugify']]
        tags:
            -  { name: console.command }

    import.command.xml_reader_company_command:
        class: Exprating\ImportXmlBundle\Command\XmlReaderCompanyCommand
        calls:
            - [setEm, ['@doctrine.orm.entity_manager']]
            - [setXmlReader, ['@exprating_import.xml.xml_reader']]
            - [setSlugify, ['@appbundle.slugify']]
        tags:
            -  { name: console.command }

    exprating_import_xml.filesystem.admitad_files:
        class: Exprating\ImportXmlBundle\Filesystem\AdmitadFiles
        arguments: [ '%kernel.root_dir%' ]

    exprating_import_xml.filesystem.admitad_price_list_files:
        class: Exprating\ImportXmlBundle\Filesystem\AdmitadPriceListFiles
        arguments: [ '%kernel.root_dir%' ]

    exprating_import_xml.command.admitad_download_command:
        class: Exprating\ImportXmlBundle\Command\AdmitadDownloadCommand
        calls:
            - [ 'setAdmitadFiles', [ '@exprating_import_xml.filesystem.admitad_files' ] ]
        tags:
            - { name: console.command }

    exprating_import_xml.command.admitad_parse_command:
        class: Exprating\ImportXmlBundle\Command\AdmitadParseCommand
        calls:
            - [ setAdmitadFiles, [ '@exprating_import_xml.filesystem.admitad_files' ] ]
            - [ setSerializer, [ '@serializer'] ]
            - [ setXmlReader, [ '@exprating_import.xml.xml_reader' ] ]
        tags:
            - { name: console.command }

    exprating_import_xml.command.admitad_download_price_lists_command:
        class: Exprating\ImportXmlBundle\Command\AdmitadDownloadPriceListsCommand
        calls:
            - [ setAdmitadPriceListFiles, [ '@exprating_import_xml.filesystem.admitad_price_list_files' ] ]
            - [ setAdmitadFiles, [ '@exprating_import_xml.filesystem.admitad_files' ] ]
            - [ setSerializer, [ '@serializer'] ]
        tags:
            - { name: console.command }

    exprating_import_xml.command.admitad_parse_price_lists_command:
        class: Exprating\ImportXmlBundle\Command\AdmitadParsePriceListsCommand
        calls:
            - [ setAdmitadPriceListFiles, [ '@exprating_import_xml.filesystem.admitad_price_list_files' ] ]
            - [ setAdmitadFiles, [ '@exprating_import_xml.filesystem.admitad_files' ] ]
            - [ setSerializer, [ '@serializer'] ]
            - [ setXmlReader, [ '@exprating_import.xml.xml_reader' ] ]
        tags:
            - { name: console.command }

    exprating_import_xml.command.offer_csv_to_db_command:
        class: Exprating\ImportXmlBundle\Command\OfferCsvToDbCommand
        calls:
            - [ setAdmitadPriceListFiles, [ '@exprating_import_xml.filesystem.admitad_price_list_files' ] ]
        tags:
            - { name: console.command }

    exprating_import_xml.serialize_normalizer.admitad_adv_normalizer:
        class: Exprating\ImportXmlBundle\Serialize\Normalizer\AdmitadAdvNormalizer
        tags:
            - { name: serializer.normalizer }

    exprating_import_xml.serialize_normalizer.offer_normalizer:
        class: Exprating\ImportXmlBundle\Serialize\Normalizer\OfferNormalizer
        tags:
            - { name: serializer.normalizer }