services:
#    exprating_import_xml.example:
#        class: Exprating\ImportXmlBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    exprating_import.xml.xml_reader:
        class: Exprating\ImportXmlBundle\Xml\XmlReader
        arguments: [ '@serializer.encoder.xml' ]
        
    exprating_import_xml.filesystem.admitad_files:
        class: Exprating\ImportXmlBundle\Filesystem\AdmitadFiles
        arguments: [ '%kernel.root_dir%' ]

    exprating_import_xml.filesystem.actionpay_files:
        class: Exprating\ImportXmlBundle\Filesystem\ActionPayFiles
        arguments: [ '%kernel.root_dir%' ]

    exprating_import_xml.filesystem.actionpay_offer_files:
        class: Exprating\ImportXmlBundle\Filesystem\ActionPayOfferFiles
        arguments: [ '%kernel.root_dir%' ]

    exprating_import_xml.filesystem.admitad_price_list_files:
        class: Exprating\ImportXmlBundle\Filesystem\AdmitadPriceListFiles
        arguments: [ '%kernel.root_dir%' ]

    exprating_import_xml.command.admitad_download_command:
        class: Exprating\ImportXmlBundle\Command\AdmitadDownloadCommand
        calls:
            - [ 'setAdmitadFiles', [ '@exprating_import_xml.filesystem.admitad_files' ] ]
        tags:
            - { name: console.command }

    exprating_import_xml.command.actionpay_download_command:
        class: Exprating\ImportXmlBundle\Command\ActionPayDownloadCommand
        calls:
            - [ 'setActionPayFiles', [ '@exprating_import_xml.filesystem.actionpay_files' ] ]
        tags:
            - { name: console.command }

    exprating_import_xml.command.actionpay_download_offers_command:
        class: Exprating\ImportXmlBundle\Command\ActionPayDownloadOffersCommand
        calls:
            - [ 'setActionPayFiles', [ '@exprating_import_xml.filesystem.actionpay_files' ] ]
            - [ 'setActionPayOfferFiles', [ '@exprating_import_xml.filesystem.actionpay_offer_files' ] ]
            - [ setSerializer, [ '@serializer'] ]
        tags:
            - { name: console.command }

    exprating_import_xml.command.actionpay_parse_offers_command:
        class: Exprating\ImportXmlBundle\Command\ActionPayParseOffersCommand
        calls:
            - [ 'setActionPayOfferFiles', [ '@exprating_import_xml.filesystem.actionpay_offer_files' ] ]
            - [ 'setAdmitadFiles', [ '@exprating_import_xml.filesystem.admitad_files' ] ]
            - [ setSerializer, [ '@serializer'] ]
        tags:
            - { name: console.command }

    exprating_import_xml.command.actionpay_parse_command:
        class: Exprating\ImportXmlBundle\Command\ActionPayParseCommand
        calls:
            - [ 'setActionPayFiles', [ '@exprating_import_xml.filesystem.actionpay_files' ] ]
            - [ setSerializer, [ '@serializer'] ]
        tags:
            - { name: console.command }

    exprating_import_xml.command.admitad_parse_command:
        class: Exprating\ImportXmlBundle\Command\AdmitadParseCommand
        calls:
            - [ setAdmitadFiles, [ '@exprating_import_xml.filesystem.admitad_files' ] ]
            - [ setSerializer, [ '@serializer'] ]
            - [ setXmlReader, [ '@exprating_import.xml.xml_reader' ] ]
        tags:
            - { name: console.command }

    exprating_import_xml.command.admitad_download_price_lists_command:
        class: Exprating\ImportXmlBundle\Command\AdmitadDownloadPriceListsCommand
        calls:
            - [ setActionPayOfferFiles, [ '@exprating_import_xml.filesystem.actionpay_offer_files' ] ]
            - [ setAdmitadPriceListFiles, [ '@exprating_import_xml.filesystem.admitad_price_list_files' ] ]
            - [ setAdmitadFiles, [ '@exprating_import_xml.filesystem.admitad_files' ] ]
            - [ setSerializer, [ '@serializer'] ]
        tags:
            - { name: console.command }

    exprating_import_xml.command.offer_parse_command:
        class: Exprating\ImportXmlBundle\Command\OfferParseCommand
        calls:
            - [ setAdmitadPriceListFiles, [ '@exprating_import_xml.filesystem.admitad_price_list_files' ] ]
            - [ setAdmitadFiles, [ '@exprating_import_xml.filesystem.admitad_files' ] ]
            - [ setSerializer, [ '@serializer'] ]
            - [ setXmlReader, [ '@exprating_import.xml.xml_reader' ] ]
            - [ setEmImportXml, [ '@doctrine.orm.entity_manager' ] ]
        tags:
            - { name: console.command }

    exprating_import_xml.command.offer_csv_to_db_command:
        class: Exprating\ImportXmlBundle\Command\OfferCsvToDbCommand
        calls:
            - [ setAdmitadPriceListFiles, [ '@exprating_import_xml.filesystem.admitad_price_list_files' ] ]
            - [ setEmImportXml, [ '@doctrine.orm.entity_manager' ] ]
        tags:
            - { name: console.command }

    exprating_import_xml.serialize_normalizer.admitad_adv_normalizer:
        class: Exprating\ImportXmlBundle\Serialize\Normalizer\AdmitadAdvNormalizer
        tags:
            - { name: serializer.normalizer }

    exprating_import_xml.serialize_normalizer.actionpay_offer_normalizer:
        class: Exprating\ImportXmlBundle\Serialize\Normalizer\ActionPayOfferNormalizer
        tags:
            - { name: serializer.normalizer }

    exprating_import_xml.serialize_normalizer.actionpay_offer_csv_normalizer:
        class: Exprating\ImportXmlBundle\Serialize\Normalizer\ActionPayOfferCsvNormalizer
        tags:
            - { name: serializer.normalizer }

    exprating_import_xml.serialize_normalizer.offer_normalizer:
        class: Exprating\ImportXmlBundle\Serialize\Normalizer\OfferNormalizer
        tags:
            - { name: serializer.normalizer }