<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160212153324 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE category CHANGE slug slug VARCHAR(255) NOT NULL COMMENT \'уникальное название на латинице. Используется для ссылки\', CHANGE parent_id parent_id VARCHAR(255) DEFAULT NULL COMMENT \'уникальное название на латинице. Используется для ссылки\', CHANGE tree_root tree_root VARCHAR(255) DEFAULT NULL COMMENT \'уникальное название на латинице. Используется для ссылки\', CHANGE name name VARCHAR(255) NOT NULL COMMENT \'Название категории\', CHANGE lft lft INT NOT NULL COMMENT \'Поле формируется автоматически для дерева.\', CHANGE lvl lvl INT NOT NULL COMMENT \'Уровень вложенности внутри дерева. Формируется автоматически.\', CHANGE rgt rgt INT NOT NULL COMMENT \'Полу формируется автоматически для дерева.\'');
        $this->addSql('ALTER TABLE category_characteristic CHANGE category_id category_id VARCHAR(255) NOT NULL COMMENT \'уникальное название на латинице. Используется для ссылки\', CHANGE characteristic_id characteristic_id VARCHAR(255) NOT NULL COMMENT \'Уникальный идентфикатор характерстики\'');
        $this->addSql('ALTER TABLE comment CHANGE full_name full_name VARCHAR(255) NOT NULL COMMENT \'Полное имя автора комментария\', CHANGE message message LONGTEXT NOT NULL COMMENT \'Сообщение комментария\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'Дата создания пользователя. Или дата его регистрации.\'');
        $this->addSql('ALTER TABLE feedback CHANGE advantages advantages VARCHAR(4000) DEFAULT NULL COMMENT \'Достоинства товара\', CHANGE disadvantages disadvantages VARCHAR(4000) DEFAULT NULL COMMENT \'Недостатки товара\', CHANGE comment comment LONGTEXT NOT NULL COMMENT \'Комментарий\', CHANGE is_like is_like TINYINT(1) DEFAULT NULL COMMENT \'Понравился ли товар\', CHANGE full_name full_name VARCHAR(255) NOT NULL COMMENT \'Полное имя автора отзыва\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'Дата создания отзыва\'');
        $this->addSql('ALTER TABLE image CHANGE filename filename VARCHAR(255) NOT NULL COMMENT \'Уникальное имя файла без пути\', CHANGE alt alt VARCHAR(255) DEFAULT NULL COMMENT \'Заполнения для тега в картинке\', CHANGE name name VARCHAR(255) NOT NULL COMMENT \'Имя картинки\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'Дата создания картинки\', CHANGE is_main is_main TINYINT(1) NOT NULL COMMENT \'На странице товара эта картинка будет отображаться первой в списке\'');
        $this->addSql('ALTER TABLE manufacturer CHANGE name name VARCHAR(255) NOT NULL COMMENT \'Название изготовителя\', CHANGE description description LONGTEXT NOT NULL COMMENT \'Описание изготовителя, видно на странице товара\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'Дата создания записи\', CHANGE image image VARCHAR(255) NOT NULL COMMENT \'имя файла картинки изготовителя\'');
        $this->addSql('ALTER TABLE product CHANGE category_id category_id VARCHAR(255) DEFAULT NULL COMMENT \'уникальное название на латинице. Используется для ссылки\', CHANGE name name VARCHAR(255) NOT NULL COMMENT \'Наименование товара\', CHANGE slug slug VARCHAR(255) NOT NULL COMMENT \'Наименование для использования в ссылке, уникально\', CHANGE preview_image preview_image VARCHAR(255) DEFAULT NULL COMMENT \'Картинка превью, показывается в списках товаров\', CHANGE min_price min_price NUMERIC(10, 2) DEFAULT NULL COMMENT \'Минимальная найденная цена на товар, среди всех продавцов. Ставится во время импорта товаров\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'Дата создания записи\', CHANGE rating rating INT DEFAULT NULL COMMENT \'Общий рейтинг товара. Автоматически ставится после создания обзора, на основе других оценок.\', CHANGE advantages advantages LONGTEXT DEFAULT NULL COMMENT \'Список достоинств товара. Сериализованный массив строк(DC2Type:json_array)\', CHANGE disadvantages disadvantages LONGTEXT DEFAULT NULL COMMENT \'Список недостатков товара. Сериализованный массив строк(DC2Type:json_array)\', CHANGE expert_opinion expert_opinion LONGTEXT DEFAULT NULL COMMENT \'Краткое мнение эксперта о товаре. Отображается на странице эксперта\', CHANGE rating1 rating1 INT DEFAULT NULL COMMENT \'Оценка №1, описание за что оценка, зависит от Категории и прописано здесь RatingSettings\', CHANGE rating2 rating2 INT DEFAULT NULL COMMENT \'Оценка №2, описание за что оценка, зависит от Категории и прописано здесь RatingSettings\', CHANGE rating3 rating3 INT DEFAULT NULL COMMENT \'Оценка №3, описание за что оценка, зависит от Категории и прописано здесь RatingSettings\', CHANGE rating4 rating4 INT DEFAULT NULL COMMENT \'Оценка №4, описание за что оценка, зависит от Категории и прописано здесь RatingSettings\', CHANGE is_enabled is_enabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Будет ли товар отображаться на сайте. Означает что на товар готово экспертное мнение и оно одобрена модератором.\', CHANGE enabled_at enabled_at DATETIME DEFAULT NULL COMMENT \'Дата написания обзора и одобрения модератором\', CHANGE visits_count visits_count BIGINT DEFAULT 0 NOT NULL COMMENT \'Количество просмотров товара\'');
        $this->addSql('ALTER TABLE product_shop_price CHANGE price price NUMERIC(10, 2) NOT NULL COMMENT \'Цена товара в этом магазине\'');
        $this->addSql('ALTER TABLE rating_settings CHANGE category_id category_id VARCHAR(255) NOT NULL COMMENT \'уникальное название на латинице. Используется для ссылки\', CHANGE rating1label rating1label VARCHAR(255) NOT NULL COMMENT \'Название оценки №1, заполняется админом категорий\', CHANGE rating2label rating2label VARCHAR(255) NOT NULL COMMENT \'Название оценки №2\', CHANGE rating3label rating3label VARCHAR(255) NOT NULL COMMENT \'Название оценки №3\', CHANGE rating4label rating4label VARCHAR(255) NOT NULL COMMENT \'Название оценки №4\', CHANGE rating1weight rating1weight INT DEFAULT 25 COMMENT \'Вес оценки №1, используется для подсчета общей оценки товара\', CHANGE rating2weight rating2weight INT DEFAULT 25 COMMENT \'Вес оценки №1\', CHANGE rating3weight rating3weight INT DEFAULT 25 COMMENT \'Вес оценки №1\', CHANGE rating4weight rating4weight INT DEFAULT 25 COMMENT \'Вес оценки №1\'');
        $this->addSql('ALTER TABLE shop CHANGE name name VARCHAR(255) NOT NULL COMMENT \'Название магазина\', CHANGE image image VARCHAR(255) NOT NULL COMMENT \'Картинка превью магазина\'');
        $this->addSql('ALTER TABLE fos_user CHANGE full_name full_name VARCHAR(255) DEFAULT NULL COMMENT \'Полное имя Эксперта\', CHANGE avatar_image avatar_image VARCHAR(255) DEFAULT NULL COMMENT \'Аватар картинка эксперта\', CHANGE birthday birthday DATE DEFAULT NULL COMMENT \'Дата рождения эксперта\', CHANGE city city VARCHAR(255) DEFAULT NULL COMMENT \'город. Отображается на странице эксперта\', CHANGE caption caption VARCHAR(255) DEFAULT NULL COMMENT \'Подпись эксперта, показывается в списке экспертов\'');
        $this->addSql('ALTER TABLE user_category CHANGE category_id category_id VARCHAR(255) NOT NULL COMMENT \'уникальное название на латинице. Используется для ссылки\'');
        $this->addSql('ALTER TABLE characteristic CHANGE slug slug VARCHAR(255) NOT NULL COMMENT \'Уникальный идентфикатор характерстики\', CHANGE name name VARCHAR(255) NOT NULL COMMENT \'Название характеристики\', CHANGE `label` `label` VARCHAR(255) NOT NULL COMMENT \'Метка характеристики, может быть не уникальна. Для использования на странице товара.\', CHANGE type type VARCHAR(255) DEFAULT \'string\' NOT NULL COMMENT \'Тип значения, используется для поиска по характеристикам.\', CHANGE scale scale VARCHAR(255) DEFAULT NULL COMMENT \'Единица измерения\', CHANGE head_group head_group VARCHAR(255) DEFAULT NULL COMMENT \'Группа к которой принадлежит характеристика. Используется при отображении характеристик на странице товара.\'');
        $this->addSql('ALTER TABLE product_characteristic CHANGE characteristic_id characteristic_id VARCHAR(255) DEFAULT NULL COMMENT \'Уникальный идентфикатор характерстики\', CHANGE value_string value_string VARCHAR(255) DEFAULT NULL COMMENT \'Значение характеристики товара. Строка\', CHANGE value_int value_int INT DEFAULT NULL COMMENT \'Значение характеристики товара. целочисленное\', CHANGE value_decimal value_decimal NUMERIC(10, 2) DEFAULT NULL COMMENT \'Значение характеристики товара. Цифра 0,00\'');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE category CHANGE slug slug VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE tree_root tree_root VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE parent_id parent_id VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE name name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE lft lft INT NOT NULL, CHANGE lvl lvl INT NOT NULL, CHANGE rgt rgt INT NOT NULL');
        $this->addSql('ALTER TABLE category_characteristic CHANGE category_id category_id VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE characteristic_id characteristic_id VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE characteristic CHANGE slug slug VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE name name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE `label` `label` VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE type type VARCHAR(255) DEFAULT \'string\' NOT NULL COLLATE utf8_unicode_ci, CHANGE scale scale VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE head_group head_group VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE comment CHANGE full_name full_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE message message LONGTEXT NOT NULL COLLATE utf8_unicode_ci, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE feedback CHANGE advantages advantages VARCHAR(4000) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE disadvantages disadvantages VARCHAR(4000) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE comment comment LONGTEXT NOT NULL COLLATE utf8_unicode_ci, CHANGE is_like is_like TINYINT(1) DEFAULT NULL, CHANGE full_name full_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE fos_user CHANGE full_name full_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE birthday birthday DATE DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE caption caption VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE avatar_image avatar_image VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE image CHANGE filename filename VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE alt alt VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE name name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE is_main is_main TINYINT(1) DEFAULT \'0\' NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE manufacturer CHANGE name name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE image image VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE description description LONGTEXT NOT NULL COLLATE utf8_unicode_ci, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE product CHANGE category_id category_id VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE name name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE slug slug VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE preview_image preview_image VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE expert_opinion expert_opinion LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE advantages advantages LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json_array)\', CHANGE disadvantages disadvantages LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json_array)\', CHANGE min_price min_price NUMERIC(10, 2) DEFAULT NULL, CHANGE rating rating INT DEFAULT NULL, CHANGE rating1 rating1 INT DEFAULT NULL, CHANGE rating2 rating2 INT DEFAULT NULL, CHANGE rating3 rating3 INT DEFAULT NULL, CHANGE rating4 rating4 INT DEFAULT NULL, CHANGE is_enabled is_enabled TINYINT(1) DEFAULT \'0\' NOT NULL, CHANGE enabled_at enabled_at DATETIME DEFAULT NULL, CHANGE visits_count visits_count BIGINT DEFAULT 0 NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE product_characteristic CHANGE characteristic_id characteristic_id VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE value_string value_string VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE value_int value_int INT DEFAULT NULL, CHANGE value_decimal value_decimal NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE product_shop_price CHANGE price price NUMERIC(10, 2) NOT NULL');
        $this->addSql('ALTER TABLE rating_settings CHANGE category_id category_id VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE rating1label rating1label VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE rating2label rating2label VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE rating3label rating3label VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE rating4label rating4label VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE rating1weight rating1weight INT DEFAULT 25, CHANGE rating2weight rating2weight INT DEFAULT 25, CHANGE rating3weight rating3weight INT DEFAULT 25, CHANGE rating4weight rating4weight INT DEFAULT 25');
        $this->addSql('ALTER TABLE shop CHANGE name name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE image image VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE user_category CHANGE category_id category_id VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci');
    }
}
