services:
    appbundle.slugify:
        class: Cocur\Slugify\Slugify
    appbundle.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ['@twig', '@doctrine.orm.entity_manager']
        public: false
        tags:
            - { name: twig.extension }
