services:
    appbundle.slugify:
        class: Cocur\Slugify\Slugify

    appbundle.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ['@twig', '@doctrine.orm.entity_manager']
        public: false
        tags:
            - { name: twig.extension }

    validator.filter_access_rights:
        class: AppBundle\Validator\Constraints\FilterAccessRightsValidator
        arguments: ['@security.authorization_checker']
        tags:
            - { name: validator.constraint_validator, alias: 'filter_access_rights'}

    validator.rating_settings_sum_weight_validator:
        class: AppBundle\Validator\Constraints\RatingSettingsSumWeightValidator
        tags:
            - { name: validator.constraint_validator, alias: 'rating_settings_sum_weight_validator'}

    validator.unique_user_validator:
        class: AppBundle\Validator\Constraints\UniqueUserValidator
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: 'unique_user_validator'}

    app.product_voter:
        class: AppBundle\Security\ProductVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    app.invite_voter:
        class: AppBundle\Security\InviteVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    app.user_voter:
        class: AppBundle\Security\UserVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    app.category_voter:
        class: AppBundle\Security\CategoryVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    app.product_filter_voter:
        class: AppBundle\Security\ProductFilterVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    app.path_finder.product_image:
        class: AppBundle\PathFinder\ProductImage
        arguments: [ '%kernel.root_dir%' ]

    app.event_listener.pre_remove_image_listener:
        class: AppBundle\Event\Listener\PreRemoveImageListener
        arguments: [ '@app.path_finder.product_image' ]
        tags:
            - { name: doctrine.event_listener, event: preRemove, connection: default }

    app.form.create_expert_request_type:
        class: AppBundle\Form\CreateExpertRequestType
        arguments: [ '@doctrine.orm.default_entity_manager' ]
        tags:
            - { name: form.type, alias: AppBundle\Form\CreateExpertRequestType }

    app.form.category_create_type:
        class: AppBundle\Form\CategoryCreateType
        arguments: [ '@appbundle.slugify' ]
        tags:
            - { name: form.type, alias: AppBundle\Form\CategoryCreateType }

    app.humanize.product_history_diff_humanize:
        class: AppBundle\Humanize\ProductHistoryDiffHumanize

imports:
    - { resource: "subscribers.yml" }
