services:
    product_subscriber:
        class: AppBundle\Event\Subscriber\ProductSubscriber
        arguments: ['@mailer', '@doctrine.orm.entity_manager', '@twig', '@app.humanize.product_history_diff_humanize']
        tags:
            - { name: kernel.event_subscriber }

    invite_subscriber:
        class: AppBundle\Event\Subscriber\InviteSubscriber
        arguments: ['@mailer', '@doctrine.orm.entity_manager', '@twig']
        tags:
            - { name: kernel.event_subscriber }

    user_subscriber:
        class: AppBundle\Event\Subscriber\UserSubscriber
        arguments: ['@mailer', '@doctrine.orm.entity_manager', '@twig']
        tags:
            - { name: kernel.event_subscriber }

    characteristic_subscriber:
        class: AppBundle\Event\Subscriber\CharacteristicSubscriber
        arguments: ['@mailer', '@doctrine.orm.entity_manager', '@twig', '@appbundle.slugify']
        tags:
            - { name: kernel.event_subscriber }

    app.upload_subscriber:
        class: AppBundle\Event\Subscriber\UploadSubscriber
        arguments: ['@app.path_finder.product_image', '@serializer']
        tags:
            - {name: kernel.event_subscriber}

