services:
    product_subscriber:
        class: AppBundle\Event\Subscriber\ProductSubscriber
        arguments: ['@mailer', '@doctrine.orm.entity_manager', '@twig']
        tags:
            - { name: kernel.event_subscriber }
