services:
    product_subscriber:
        class: AppBundle\Event\Subscriber\ProductSubscriber
        arguments: ['@mailer', '@doctrine.orm.entity_manager', '@twig']
        tags:
            - { name: kernel.event_subscriber }

    app.upload_subscriber:
        class: AppBundle\Event\Subscriber\UploadSubscriber
        arguments: ['@app.path_finder.product_image', '@serializer']
        tags:
            - {name: kernel.event_subscriber}

