<?php

namespace Exprating\ImportXmlBundle\Repository;

use Doctrine\ORM\AbstractQuery;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $company
     *
     * @return array
     */
    public function getHashesByCompany($company)
    {
        $result = $this->createQueryBuilder('a')
            ->select('a.hash')
            ->where('a.company = :company')
            ->setParameter('company', $company)
            ->getQuery()
            ->getResult(AbstractQuery::HYDRATE_ARRAY);
        $hashes = [];
        foreach ($result as $row) {
            $hashes[$row['hash']] = true;
        }

        return $hashes;
    }

    /**
     * @param array $hashes
     */
    public function removeByHashes(array $hashes)
    {
        if (count($hashes) > 0) {
            $this->createQueryBuilder('a')
                ->delete()
                ->where('a.hash IN (:hash)')
                ->setParameter('hash', $hashes)
                ->getQuery()
                ->execute();
        }
    }
}
