<?php

namespace Exprating\ImportBundle\Repository;

/**
 * AliasCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliasCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
