<?php

namespace Exprating\ImportBundle\Repository;

/**
 * AliasItemRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliasItemRepository extends \Doctrine\ORM\EntityRepository
{
}
