services:
    import.command.repair_tree_rubrics_command:
        class: Exprating\ImportBundle\Command\ImportRubricsToCategoryCommand
        calls:
            - [setEm, ['@doctrine.orm.entity_manager']]
            - [setEmImport, ['@doctrine.orm.import_entity_manager']]
            - [setSlugify, ['@appbundle.slugify']]
        tags:
            -  { name: console.command }