services:
    import.command.alias_category_command:
        class: Exprating\ImportBundle\Command\AliasCategoryCommand
        calls:
            - [setEm, ['@doctrine.orm.entity_manager']]
            - [setEmImport, ['@doctrine.orm.import_entity_manager']]
            - [setSlugify, ['@appbundle.slugify']]
            - [setEvalTextRus, ['@import.exval_text_rus']]
        tags:
            -  { name: console.command }

    import.command.import_item_command:
        class: Exprating\ImportBundle\Command\ImportItemCommand
        calls:
            - [setEm, ['@doctrine.orm.entity_manager']]
            - [setEmImport, ['@doctrine.orm.import_entity_manager']]
            - [setSlugify, ['@appbundle.slugify']]
            - [setRootDir, ['%kernel.root_dir%']]
        tags:
            -  { name: console.command }

    import.command.repair_category_command:
        class: Exprating\ImportBundle\Command\RepairCategoryCommand
        calls:
            - [setEm, ['@doctrine.orm.entity_manager']]
        tags:
            -  { name: console.command }

    import.command.xml_reader_command:
        class: Exprating\ImportBundle\Command\XmlReaderCommand
        calls:
            - [setEm, ['@doctrine.orm.entity_manager']]
            - [setXmlReader, ['@exprating_import.xml.xml_reader']]
            - [setSlugify, ['@appbundle.slugify']]
        tags:
            -  { name: console.command }

    import.exval_text_rus:
        class: Exprating\ImportBundle\CompareText\EvalTextRus

    exprating_import.xml.xml_reader:
        class: Exprating\ImportBundle\Xml\XmlReader
        arguments: [ '@serializer.encoder.xml' ]