<?php
/**
 * Date: 29.03.16
 * Time: 15:42
 */

namespace Exprating\ImportBundle\Tests\Parser;


use Exprating\ImportBundle\Parser\OtzyvProParser;

class OtzyvProParserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @param $html
     *
     * @dataProvider getHtml
     */
    public function testParse($html)
    {
        $parser = new OtzyvProParser();
    }

    public function getHtml()
    {
        return [
            [
                '<div class="blockboxcat">
	<div class="blockboxcat_left"><ul><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_01.png" alt="Отзыв про"></span>
										<a href="/category/avto-i-moto/" class="href" title="">Авто и мото</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/avto-i-moto/avtozapchasti/" title="">Автозапчасти</a><a href="/category/avto-i-moto/avtohimiya-i-masla/" title="">Автохимия и масла</a><a href="/category/avto-i-moto/aksessuaryi-dlya-avto/" title="">Аксессуары для авто</a><a href="/category/avto-i-moto/vodnyiy-transport/" title="">Водный транспорт</a><a href="/category/avto-i-moto/gruzovyie-avtomobili/" title="">Грузовые автомобили</a><a href="/category/avto-i-moto/doma-na-kolesah/" title="">Дома на колесах</a><a href="/category/avto-i-moto/legkovyie-avto/" title="">Легковые авто</a><a href="/category/avto-i-moto/moto/" title="">Мото</a><a href="/category/avto-i-moto/raznoe_auto_moto/" title="">Разное (авто и мото)</a><a href="/category/avto-i-moto/shinyi-i-diski/" title="">Шины и диски</a><a href="/category/avto-i-moto/elektronika-dlya-avto/" title="">Электроника для авто</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_02.png" alt="Отзыв про"></span>
										<a href="/category/organizatsii/" class="href" title="">Организации</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/organizatsii/avtosalonyi-i-avtoryinki/" title="">Автосалоны и авторынки</a><a href="/category/organizatsii/avtoservisyi/" title="">Автосервисы</a><a href="/category/organizatsii/avtostoyanki-i-parkingi/" title="">Автостоянки и паркинги</a><a href="/category/organizatsii/avtoshkolyi/" title="">Автошколы</a><a href="/category/organizatsii/agentstva-nedvijimosti/" title="">Агентства недвижимости</a><a href="/category/organizatsii/apteki/" title="">Аптеки</a><a href="/category/organizatsii/bazaryi-ryinki-yarmarki/" title="">Базары, рынки, ярмарки</a><a href="/category/organizatsii/bani-i-saunyi/" title="">Бани и сауны</a><a href="/category/organizatsii/banki/" title="">Банки</a><a href="/category/organizatsii/bolnitsyi-i-kliniki/" title="">Больницы и клиники</a><a href="/category/organizatsii/veterinarnyie-kliniki-i-apteki/" title="">Ветеринарные клиники и аптеки</a><a href="/category/organizatsii/gostinitsyi-i-priyutyi-domashnih-jivotnyih/" title="">Гостиницы и приюты домашних животных</a><a href="/category/organizatsii/zooparki-delfinarii-okeanariumyi/" title="">Зоопарки, дельфинарии, океанариумы</a><a href="/category/organizatsii/kinoteatryi/" title="">Кинотеатры</a><a href="/category/organizatsii/klubyi-po-interesam/" title="">Клубы по интересам</a><a href="/category/organizatsii/kompanii-i-predpriyatiya/" title="">Компании и предприятия</a><a href="/category/organizatsii/magazinyi-i-torgovyie-tsentryi/" title="">Магазины и торговые центры</a><a href="/category/organizatsii/muzei-i-vyistavki/" title="">Музеи и выставки</a><a href="/category/organizatsii/muzyikalnyie-shkolyi/" title="">Музыкальные школы</a><a href="/category/organizatsii/obrazovanie/" title="">Образование</a><a href="/category/organizatsii/obschestvennyiy-transport-i-gruzoperevozki/" title="">Общественный транспорт и грузоперевозки</a><a href="/category/organizatsii/parki-attraktsionov/" title="">Парки аттракционов</a><a href="/category/organizatsii/parki-kulturyi-i-otdyiha/" title="">Парки культуры и отдыха</a><a href="/category/organizatsii/raznoe_city/" title="">Разное (в городе)</a><a href="/category/organizatsii/restoranyi-baryi-kafe/" title="">Рестораны, бары, кафе</a><a href="/category/organizatsii/salonyi-krasotyi/" title="">Салоны красоты</a><a href="/category/organizatsii/stadionyi-i-sportivnyie-klubyi/" title="">Стадионы и спортивные клубы</a><a href="/category/organizatsii/teatryi/" title="">Театры</a><a href="/category/organizatsii/torgovo-razvlekatelnyie-tsentryi/" title="">Торгово-развлекательные центры</a><a href="/category/organizatsii/tsirki/" title="">Цирки</a><a href="/category/organizatsii/cherniy-spisok/" title="">Черный список</a><a href="/category/organizatsii/zhilye-kompleksy/" title="">Жилые комплексы (ЖК)</a><a href="/category/organizatsii/kottedzhnye-poselki/" title="">Коттеджные поселки</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_03.png" alt="Отзывы"></span>
										<a href="/category/vse-dlya-doma-i-sada/" class="href" title="">Все для дома и сада</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/vse-dlya-doma-i-sada/basseynyi-dlya-dachi/" title="">Бассейны для дачи</a><a href="/category/vse-dlya-doma-i-sada/borba-s-nasekomyimi-i-gryizunami/" title="">Борьба с насекомыми и грызунами</a><a href="/category/vse-dlya-doma-i-sada/byitovaya-himiya/" title="">Бытовая химия</a><a href="/category/vse-dlya-doma-i-sada/gril-i-koptilni/" title="">Гриль и коптильни</a><a href="/category/vse-dlya-doma-i-sada/mebel/" title="">Мебель</a><a href="/category/vse-dlya-doma-i-sada/okna-i-dveri/" title="">Окна и двери</a><a href="/category/vse-dlya-doma-i-sada/posuda-i-stolovyie-priboryi/" title="">Посуда и столовые приборы</a><a href="/category/vse-dlya-doma-i-sada/raznoe_dom_sad/" title="">Разное (дом и сад)</a><a href="/category/vse-dlya-doma-i-sada/sad-i-ogorod/" title="">Сад и огород</a><a href="/category/vse-dlya-doma-i-sada/santehnika/" title="">Сантехника</a><a href="/category/vse-dlya-doma-i-sada/svetotehnika-i-osveschenie/" title="">Светотехника и освещение</a><a href="/category/vse-dlya-doma-i-sada/signalizatsii-i-ohrana-territorii/" title="">Сигнализации и охрана территории</a><a href="/category/vse-dlya-doma-i-sada/stroitelnyie-materialyi/" title="">Строительные материалы</a><a href="/category/vse-dlya-doma-i-sada/filtryi-vodyi/" title="">Фильтры воды</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_04.png" alt="Отзыв про"></span>
										<a href="/category/bankovskie-uslugi-i-strahovanie/" class="href" title="">Банковские услуги и Страхование</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/bankovskie-uslugi-i-strahovanie/strahovanie/" title="">Страхование</a><a href="/category/bankovskie-uslugi-i-strahovanie/denejnyie-perevodyi/" title="">Денежные переводы</a><a href="/category/bankovskie-uslugi-i-strahovanie/kreditovanie-i-lizing/" title="">Кредитование и лизинг</a><a href="/category/bankovskie-uslugi-i-strahovanie/plastikovyie-kartyi/" title="">Пластиковые карты</a><a href="/category/bankovskie-uslugi-i-strahovanie/platejnyie-sistemyi/" title="">Платежные системы</a><a href="/category/bankovskie-uslugi-i-strahovanie/raznoe_dengi/" title="">Разное (переводы, денежные системы)</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_05.png" alt="Отзыв про"></span>
										<a href="/category/deti-i-roditeli/" class="href" title="">Дети и родители</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/deti-i-roditeli/vse-dlya-shkolyi/" title="">Все для школы</a><a href="/category/deti-i-roditeli/detskaya-mebel/" title="">Детская мебель</a><a href="/category/deti-i-roditeli/detskaya-santehnika/" title="">Детская сантехника</a><a href="/category/deti-i-roditeli/detskie-podguzniki/" title="">Детские подгузники</a><a href="/category/deti-i-roditeli/detskie-trenajeryi/" title="">Детские тренажеры</a><a href="/category/deti-i-roditeli/igrovyie-ploschadki-i-razvlecheniya/" title="">Игровые площадки и развлечения</a><a href="/category/deti-i-roditeli/igrushki/" title="">Игрушки</a><a href="/category/deti-i-roditeli/pitanie-dlya-mam/" title="">Питание для мам</a><a href="/category/deti-i-roditeli/posuda-i-kormlenie-detey/" title="">Посуда и кормление детей</a><a href="/category/deti-i-roditeli/raznoe_deti/" title="">Разное (дети и родители)</a><a href="/category/deti-i-roditeli/sredstva-gigienyi/" title="">Средства гигиены</a><a href="/category/deti-i-roditeli/sredstva-nablyudeniya-i-kontrolya/" title="">Средства наблюдения и контроля</a><a href="/category/deti-i-roditeli/transportirovka-detey/" title="">Транспортировка детей</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_06.png" alt="Отзыв про"></span>
										<a href="/category/zhivotnye-i-komnatnye-rasteniya/" class="href" title="">Животные и комнатные растения</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/zhivotnye-i-komnatnye-rasteniya/veterinarnyie-sredstva/" title="">Ветеринарные средства</a><a href="/category/zhivotnye-i-komnatnye-rasteniya/domashnie-jivotnyie/" title="">Домашние животные</a><a href="/category/zhivotnye-i-komnatnye-rasteniya/korm-dlya-jivotnyih/" title="">Корм для животных</a><a href="/category/zhivotnye-i-komnatnye-rasteniya/raznoe_givotnie_rast/" title="">Разное (животные и растения)</a><a href="/category/zhivotnye-i-komnatnye-rasteniya/rasteniya-komnatnyie/" title="">Растения комнатные</a><a href="/category/zhivotnye-i-komnatnye-rasteniya/rasteniya-sadovyie/" title="">Растения садовые</a><a href="/category/zhivotnye-i-komnatnye-rasteniya/tovaryi-dlya-jivotnyih/" title="">Товары для животных</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_07.png" alt="Отзыв про"></span>
										<a href="/category/igry/" class="href" title="">Игры</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/igry/igrovyie-pristavki/" title="">Игровые приставки</a><a href="/category/igry/igryi-dlya-Nintendo-Wii/" title="">Игры для Nintendo Wii</a><a href="/category/igry/igryi-dlya-PSP/" title="">Игры для PSP</a><a href="/category/igry/igryi-dlya-Sony-PlayStation-2/" title="">Игры для Sony PlayStation 2</a><a href="/category/igry/igryi-dlya-Sony-PlayStation-3/" title="">Игры для Sony PlayStation 3</a><a href="/category/igry/igryi-dlya-Xbox/" title="">Игры для Xbox</a><a href="/category/igry/igryi-dlya-telefonov/" title="">Игры для телефонов</a><a href="/category/igry/kompyuternyie-igryi/" title="">Компьютерные игры</a><a href="/category/igry/loterei-i-rozyigryishi/" title="">Лотереи и розыгрыши</a><a href="/category/igry/na-prirode/" title="">На природе</a><a href="/category/igry/nastolnyie-igryi/" title="">Настольные игры</a><a href="/category/igry/raznoe_igry/" title="">Разное (игры)</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_08.png" alt="Отзывпро вход"></span>
										<a href="/category/internet-i-sayty/" class="href" title="">Интернет и сайты</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/internet-i-sayty/veb-masteru/" title="">Веб-мастеру</a><a href="/category/internet-i-sayty/internet-magazinyi/" title="">Интернет-магазины</a><a href="/category/internet-i-sayty/onlayn-servisyi/" title="">Онлайн-сервисы</a><a href="/category/internet-i-sayty/raznoe_saity/" title="">Разное (сайты)</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_09.png" alt="Отзыв про"></span>
										<a href="/category/knigi-zhurnaly/" class="href" title="">Книги, журналы</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/knigi-zhurnaly/audioknigi/" title="">Аудиокниги</a><a href="/category/knigi-zhurnaly/gazetyi/" title="">Газеты</a><a href="/category/knigi-zhurnaly/jurnalyi/" title="">Журналы</a><a href="/category/knigi-zhurnaly/katalogi-produktsii/" title="">Каталоги продукции</a><a href="/category/knigi-zhurnaly/knigi/" title="">Книги</a><a href="/category/knigi-zhurnaly/pisateli/" title="">Писатели</a><a href="/category/knigi-zhurnaly/raznoe_knigi_gurnaly/" title="">Разное (книги, журналы)</a></div>
									</li></ul></div>
	<div class="blockboxcat_right"><ul><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_10.png" alt="Сайт отзыв про"></span>
										<a href="/category/kompyutery-i-programmy/" class="href" title="">Компьютеры и программы</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/kompyutery-i-programmy/aksessuaryi/" title="">Аксессуары</a><a href="/category/kompyutery-i-programmy/akustika-dlya-kompyuterov/" title="">Акустика для компьютеров</a><a href="/category/kompyutery-i-programmy/veb-kameryi/" title="">Веб-камеры</a><a href="/category/kompyutery-i-programmy/vneshnie-USB-nakopiteli/" title="">Внешние USB-накопители</a><a href="/category/kompyutery-i-programmy/istochniki-bespereboynogo-pitaniya-UPS/" title="">Источники бесперебойного питания (UPS)</a><a href="/category/kompyutery-i-programmy/karmannyie-pk/" title="">Карманные ПК</a><a href="/category/kompyutery-i-programmy/kartyi-pamyati/" title="">Карты памяти</a><a href="/category/kompyutery-i-programmy/komplektuyuschie/" title="">Комплектующие</a><a href="/category/kompyutery-i-programmy/kopiryi-kopirovalnyie-apparatyi/" title="">Копиры, копировальные аппараты</a><a href="/category/kompyutery-i-programmy/manipulyatoryi-i-klaviaturyi/" title="">Манипуляторы и клавиатуры</a><a href="/category/kompyutery-i-programmy/monitoryi/" title="">Мониторы</a><a href="/category/kompyutery-i-programmy/monobloki/" title="">Моноблоки</a><a href="/category/kompyutery-i-programmy/multimedia/" title="">Мультимедиа</a><a href="/category/kompyutery-i-programmy/nastolnyie-kompyuteryi/" title="">Настольные компьютеры</a><a href="/category/kompyutery-i-programmy/netbuki/" title="">Нетбуки</a><a href="/category/kompyutery-i-programmy/noutbuki/" title="">Ноутбуки</a><a href="/category/kompyutery-i-programmy/planshetnyie-pk/" title="">Планшетные ПК</a><a href="/category/kompyutery-i-programmy/printeryi-i-mfu/" title="">Принтеры и МФУ</a><a href="/category/kompyutery-i-programmy/programmnoe-obespechenie/" title="">Программное обеспечение</a><a href="/category/kompyutery-i-programmy/raznoe_pc_progs/" title="">Разное (компьютеры и программы)</a><a href="/category/kompyutery-i-programmy/rashodnyie-materialyi/" title="">Расходные материалы</a><a href="/category/kompyutery-i-programmy/serveryi/" title="">Серверы</a><a href="/category/kompyutery-i-programmy/setevoe-oborudovanie/" title="">Сетевое оборудование</a><a href="/category/kompyutery-i-programmy/skaneryi/" title="">Сканеры</a><a href="/category/kompyutery-i-programmy/ustroystva-dlya-chteniya-kart-pamyati/" title="">Устройства для чтения карт памяти</a><a href="/category/kompyutery-i-programmy/elektronnyie-knigi/" title="">Электронные книги</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_11.png" alt="Отзыв про"></span>
										<a href="/category/krasota-i-zdorove/" class="href" title="">Красота и здоровье</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/krasota-i-zdorove/alternativnaya-meditsina/" title="">Альтернативная медицина</a><a href="/category/krasota-i-zdorove/kosmetika-dekorativnaya/" title="">Косметика декоративная</a><a href="/category/krasota-i-zdorove/kosmetika-uhajivayuschaya/" title="">Косметика ухаживающая</a><a href="/category/krasota-i-zdorove/kosmeticheskie-prinadlejnosti/" title="">Косметические принадлежности</a><a href="/category/krasota-i-zdorove/kosmeticheskie-protseduryi/" title="">Косметические процедуры</a><a href="/category/krasota-i-zdorove/lekarstvennyie-sredstva/" title="">Лекарственные средства</a><a href="/category/krasota-i-zdorove/metodyi-lecheniya-i-operatsii/" title="">Методы лечения и операции</a><a href="/category/krasota-i-zdorove/ochki-i-kontaktnyie-linzyi/" title="">Очки и контактные линзы</a><a href="/category/krasota-i-zdorove/parfyumeriya-i-dezodorantyi/" title="">Парфюмерия и дезодоранты</a><a href="/category/krasota-i-zdorove/raznoe_kras_zdor/" title="">Разное (красота и здоровье)</a><a href="/category/krasota-i-zdorove/sredstva-gigienyi/" title="">Средства гигиены</a><a href="/category/krasota-i-zdorove/sredstva-dlya-pohudeniya/" title="">Средства для похудения</a><a href="/category/krasota-i-zdorove/sredstva-kontratseptsii/" title="">Средства контрацепции</a><a href="/category/krasota-i-zdorove/sredstva-uvelicheniya-grudi/" title="">Средства увеличения груди</a><a href="/category/krasota-i-zdorove/strijki-i-pricheski-dlya-volos/" title="">Стрижки и прически для волос</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_12.png" alt="Отзыв про"></span>
										<a href="/category/odezhda-i-obuv/" class="href" title="">Одежда и обувь</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/odezhda-i-obuv/aksessuaryi/" title="">Аксессуары</a><a href="/category/odezhda-i-obuv/obuv-detskaya/" title="">Обувь детская</a><a href="/category/odezhda-i-obuv/obuv-jenskaya/" title="">Обувь женская</a><a href="/category/odezhda-i-obuv/obuv-mujskaya/" title="">Обувь мужская</a><a href="/category/odezhda-i-obuv/odejda-detskaya/" title="">Одежда детская</a><a href="/category/odezhda-i-obuv/odejda-jenskaya/" title="">Одежда женская</a><a href="/category/odezhda-i-obuv/odejda-mujskaya/" title="">Одежда мужская</a><a href="/category/odezhda-i-obuv/postelnoe-bele/" title="">Постельное белье</a><a href="/category/odezhda-i-obuv/raznoe_ode_obuv/" title="">Разное (одежда и обувь)</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_13.png" alt="Отзыв про"></span>
										<a href="/category/podarki-i-suveniry/" class="href" title="">Подарки и сувениры</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/podarki-i-suveniry/antistressovyie-i-relaksiruyuschie-suveniryi/" title="">Антистрессовые и релаксирующие сувениры</a><a href="/category/podarki-i-suveniry/intimnyie-podarki/" title="">Интимные подарки</a><a href="/category/podarki-i-suveniry/podarki-po-reklamnoy-aktsii/" title="">Подарки по рекламной акции</a><a href="/category/podarki-i-suveniry/raznoe_podarki/" title="">Разное (подарки и сувениры)</a><a href="/category/podarki-i-suveniry/tabachnyie-izdeliya/" title="">Табачные изделия</a><a href="/category/podarki-i-suveniry/tovaryi-dlya-rukodeliya/" title="">Товары для рукоделия</a><a href="/category/podarki-i-suveniry/chasyi/" title="">Часы</a><a href="/category/podarki-i-suveniry/yuvelirnyie-ukrasheniya-i-bijuteriya/" title="">Ювелирные украшения и бижутерия</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_14.png" alt="Отзыв про"></span>
										<a href="/category/produkty-pitaniya/" class="href" title="">Продукты питания</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/produkty-pitaniya/alkogol/" title="">Алкоголь</a><a href="/category/produkty-pitaniya/desertyi/" title="">Десерты</a><a href="/category/produkty-pitaniya/detskoe-pitanie/" title="">Детское питание</a><a href="/category/produkty-pitaniya/zakuski/" title="">Закуски</a><a href="/category/produkty-pitaniya/konservyi/" title="">Консервы</a><a href="/category/produkty-pitaniya/krupyi-i-makaronnyie-izdeliya/" title="">Крупы и макаронные изделия</a><a href="/category/produkty-pitaniya/molochnyie-produktyi/" title="">Молочные продукты</a><a href="/category/produkty-pitaniya/myaso-i-kolbasyi/" title="">Мясо и колбасы</a><a href="/category/produkty-pitaniya/napitki/" title="">Напитки</a><a href="/category/produkty-pitaniya/natsionalnyie-blyuda/" title="">Национальные блюда</a><a href="/category/produkty-pitaniya/orehi-i-semechki/" title="">Орехи и семечки</a><a href="/category/produkty-pitaniya/pischevyie-dobavki/" title="">Пищевые добавки</a><a href="/category/produkty-pitaniya/polufabrikatyi/" title="">Полуфабрикаты</a><a href="/category/produkty-pitaniya/pripravyi-i-spetsii/" title="">Приправы и специи</a><a href="/category/produkty-pitaniya/raznoe_produkty/" title="">Разное (продукты питания)</a><a href="/category/produkty-pitaniya/rastitelnyie-masla/" title="">Растительные масла</a><a href="/category/produkty-pitaniya/sahar-i-saharozameniteli/" title="">Сахар и сахарозаменители</a><a href="/category/produkty-pitaniya/sousyi-i-podlivyi/" title="">Соусы и подливы</a><a href="/category/produkty-pitaniya/hlebobulochnyie-izdeliya/" title="">Хлебобулочные изделия</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_15.png" alt="Отзывпро"></span>
										<a href="/category/puteshestviya-i-turizm/" class="href" title="">Путешествия и туризм</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/puteshestviya-i-turizm/agentstva-i-kompanii/" title="">Агентства и компании</a><a href="/category/puteshestviya-i-turizm/kempingi-turisticheskie-bazyi-otdyiha/" title="">Кемпинги, туристические базы отдыха</a><a href="/category/puteshestviya-i-turizm/kurortyi-i-ekskursii/" title="">Курорты и экскурсии</a><a href="/category/puteshestviya-i-turizm/oteli-gostinitsyi-sanatorii/" title="">Отели, гостиницы, санатории</a><a href="/category/puteshestviya-i-turizm/turyi-i-kruizyi/" title="">Туры и круизы</a><a href="/category/puteshestviya-i-turizm/festivali-i-prazdniki/" title="">Фестивали и праздники</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_16.png" alt="Отзыв про"></span>
										<a href="/category/sport-i-aktivnyy-otdyh/" class="href" title="">Спорт и активный отдых</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/sport-i-aktivnyy-otdyh/velosipedyi/" title="">Велосипеды</a><a href="/category/sport-i-aktivnyy-otdyh/vidyi-sporta/" title="">Виды спорта</a><a href="/category/sport-i-aktivnyy-otdyh/palatki-i-shatryi/" title="">Палатки и шатры</a><a href="/category/sport-i-aktivnyy-otdyh/raznoe_sport/" title="">Разное (Спорт)</a><a href="/category/sport-i-aktivnyy-otdyh/ryibolovnoe-snaryajenie/" title="">Рыболовное снаряжение</a><a href="/category/sport-i-aktivnyy-otdyh/snaryajenie-dlya-plavaniya-i-dayvinga/" title="">Снаряжение для плавания и дайвинга</a><a href="/category/sport-i-aktivnyy-otdyh/sportivnoe-snaryajenie-i-trenajeryi/" title="">Спортивное снаряжение и тренажеры</a><a href="/category/sport-i-aktivnyy-otdyh/sportivnyie-sredstva-peredvijeniya/" title="">Спортивные средства передвижения</a><a href="/category/sport-i-aktivnyy-otdyh/strelba/" title="">Стрельба</a><a href="/category/sport-i-aktivnyy-otdyh/turisticheskoe-snaryajenie/" title="">Туристическое снаряжение</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_17.png" alt="Отзыв про"></span>
										<a href="/category/tehnika-i-oborudovanie/" class="href" title="">Техника и оборудование</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/tehnika-i-oborudovanie/audio/" title="">Аудио</a><a href="/category/tehnika-i-oborudovanie/byitovaya-tehnika-dlya-individualnogo-uhoda/" title="">Бытовая техника для индивидуального ухода</a><a href="/category/tehnika-i-oborudovanie/byitovaya-tehnika-dlya-kuhni/" title="">Бытовая техника для кухни</a><a href="/category/tehnika-i-oborudovanie/byitovaya-tehnika-dlya-odejdyi-i-obuvi/" title="">Бытовая техника для одежды и обуви</a><a href="/category/tehnika-i-oborudovanie/byitovaya-tehnika-dlya-pomescheniy/" title="">Бытовая техника для помещений</a><a href="/category/tehnika-i-oborudovanie/video/" title="">Видео</a><a href="/category/tehnika-i-oborudovanie/kantselyarskie-izdeliya/" title="">Канцелярские изделия</a><a href="/category/tehnika-i-oborudovanie/kronshteynyi/" title="">Кронштейны</a><a href="/category/tehnika-i-oborudovanie/meditsinskoe-oborudovanie/" title="">Медицинское оборудование</a><a href="/category/tehnika-i-oborudovanie/muzyikalnyie-instrumentyi/" title="">Музыкальные инструменты</a><a href="/category/tehnika-i-oborudovanie/oborudovanie-dlya-spetseffektov/" title="">Оборудование для спецэффектов</a><a href="/category/tehnika-i-oborudovanie/ofisnaya-tehnika/" title="">Офисная техника</a><a href="/category/tehnika-i-oborudovanie/portativnaya-audiotehnika/" title="">Портативная аудиотехника</a><a href="/category/tehnika-i-oborudovanie/promyishlennoe-oborudovanie/" title="">Промышленное оборудование</a><a href="/category/tehnika-i-oborudovanie/raznoe_tehnika/" title="">Разное (техника)</a><a href="/category/tehnika-i-oborudovanie/sredstva-svyazi/" title="">Средства связи</a><a href="/category/tehnika-i-oborudovanie/stroitelnyiy-instrument-i-oborudovanie/" title="">Строительный инструмент и оборудование</a><a href="/category/tehnika-i-oborudovanie/tehnika-dlya-dachi/" title="">Техника для дачи</a><a href="/category/tehnika-i-oborudovanie/foto-i-optika/" title="">Фото и оптика</a><a href="/category/tehnika-i-oborudovanie/elektronnyie-priboryi/" title="">Электронные приборы</a></div>
									</li><li class="list">
										<span class="imgcat"><img src="/templates/otzyvy/images/icon_cat/cat_18.png" alt="Отзыв про"></span>
										<a href="/category/filmy-video-i-tv/" class="href" title="">Фильмы, видео и ТВ</a>
										<a href="#" title="" class="hoverbox_btn"></a>
										<div class="sub_category"><a href="/category/filmy-video-i-tv/filmyi-i-video/" title="">Фильмы и видео</a><a href="/category/filmy-video-i-tv/televidenie/" title="">Телевидение</a><a href="/category/filmy-video-i-tv/raznoe_tv/" title="">Разное (фильмы, видео и ТВ)</a></div>
									</li></ul></div>
	<div class="clear"></div>
</div>',
            ],
        ];
    }
}